import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.4";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function formatBrt(date?: string | null, brt?: string | null, locale = "pt-BR"): string {
  if (brt) return brt;
  if (!date) return "—";
  const parsed = new Date(date);
  if (Number.isNaN(parsed.getTime())) return date;
  return `${parsed.toLocaleString(locale, { timeZone: "America/Sao_Paulo" })} (BRT)`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, serviceKey);

    const authHeader = req.headers.get("Authorization");
    if (!authHeader) return new Response(JSON.stringify({ error: "Não autorizado" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });

    const { data: { user } } = await supabase.auth.getUser(authHeader.replace("Bearer ", ""));
    if (!user) return new Response(JSON.stringify({ error: "Não autorizado" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });

    const { caseId, lang = "pt" } = await req.json();
    if (!caseId) return new Response(JSON.stringify({ error: "caseId obrigatório" }), { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } });

    const { data: caseData } = await supabase.from("cases").select("*").eq("id", caseId).eq("user_id", user.id).single();
    if (!caseData) return new Response(JSON.stringify({ error: "Caso não encontrado" }), { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } });

    const { data: evidences } = await supabase.from("evidences").select("*").eq("case_id", caseId).eq("user_id", user.id).order("created_at");

    const { data: profile } = await supabase.from("profiles").select("*").eq("id", user.id).single();

    const labels = {
      pt: { title: "RELATÓRIO CONSOLIDADO DO CASO", date: "Data", module: "Módulo", hash: "Hash SHA-256", certified: "Certificado", pending: "Pendente", evidence: "Evidência", result: "Resultado da Análise", perito: "Perito Responsável", registration: "Registro", generated: "Gerado por Cortex Forense em", total: "Total de Evidências", page: "Página" },
      en: { title: "CONSOLIDATED CASE REPORT", date: "Date", module: "Module", hash: "SHA-256 Hash", certified: "Certified", pending: "Pending", evidence: "Evidence", result: "Analysis Result", perito: "Expert", registration: "Registration", generated: "Generated by Cortex Forense on", total: "Total Evidences", page: "Page" },
      es: { title: "INFORME CONSOLIDADO DEL CASO", date: "Fecha", module: "Módulo", hash: "Hash SHA-256", certified: "Certificado", pending: "Pendiente", evidence: "Evidencia", result: "Resultado del Análisis", perito: "Perito Responsable", registration: "Registro", generated: "Generado por Cortex Forense en", total: "Total de Evidencias", page: "Página" },
    };

    const l = labels[lang as keyof typeof labels] || labels.pt;

    const moduleLabels: Record<string, Record<string, string>> = {
      pt: { grafotecnia: "Grafotecnia", hives: "Leitura de Hives", documental: "Análise Documental", laudo: "Geração de Laudos", "plagio-codigo": "Plágio de Código", "email-pst": "Análise de E-mails", "web-capture": "Captura Web", "analise-imagem": "Análise de Imagens", quesitos: "Quesitos" },
      en: { grafotecnia: "Handwriting Analysis", hives: "Registry Hives", documental: "Document Analysis", laudo: "Report Generation", "plagio-codigo": "Code Plagiarism", "email-pst": "Email Analysis", "web-capture": "Web Capture", "analise-imagem": "Image Analysis", quesitos: "Legal Questions" },
      es: { grafotecnia: "Grafotecnia", hives: "Lectura de Hives", documental: "Análisis Documental", laudo: "Generación de Informes", "plagio-codigo": "Plagio de Código", "email-pst": "Análisis de Correos", "web-capture": "Captura Web", "analise-imagem": "Análisis de Imágenes", quesitos: "Preguntas Periciales" },
    };

    const ml = moduleLabels[lang as keyof typeof moduleLabels] || moduleLabels.pt;

    const evidenceRows = (evidences || []).map((ev: any, i: number) => `
      <div style="page-break-inside:avoid; border:1px solid #ddd; border-radius:8px; padding:16px; margin-bottom:16px;">
        <h3 style="margin:0 0 8px; color:#333;">${i + 1}. ${ev.title || "—"}</h3>
        <table style="width:100%; font-size:12px; border-collapse:collapse;">
          <tr><td style="width:120px; color:#666; padding:4px 0;">${l.module}:</td><td>${ml[ev.module] || ev.module}</td></tr>
          <tr><td style="color:#666; padding:4px 0;">${l.date}:</td><td>${formatBrt(ev.created_at, ev.created_at_brt || ev.metadata?.iso27037?.chainOfCustody?.acquisitionTimeBR, lang === "en" ? "en-US" : lang === "es" ? "es-ES" : "pt-BR")}</td></tr>
          <tr><td style="color:#666; padding:4px 0;">${l.hash}:</td><td style="font-family:monospace; font-size:10px; word-break:break-all;">${ev.file_hash || "—"}</td></tr>
          <tr><td style="color:#666; padding:4px 0;">Status:</td><td>${(ev.tsa_timestamp || ev.blockchain_tx) ? `✅ ${l.certified}` : `⏳ ${l.pending}`}</td></tr>
        </table>
        ${ev.result_content ? `<div style="margin-top:12px;"><strong style="font-size:11px; color:#666;">${l.result}:</strong><pre style="background:#f5f5f5; padding:12px; border-radius:6px; font-size:11px; white-space:pre-wrap; max-height:300px; overflow:auto;">${ev.result_content.replace(/</g, "&lt;")}</pre></div>` : ""}
      </div>
    `).join("");

    const html = `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<title>${l.title} — ${caseData.title}</title>
<style>
  @page { margin: 2cm; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #222; max-width: 800px; margin: 0 auto; padding: 20px; }
  .header { text-align: center; border-bottom: 3px solid #e67e22; padding-bottom: 20px; margin-bottom: 30px; }
  .header h1 { font-size: 18px; color: #e67e22; margin: 0; letter-spacing: 2px; }
  .header h2 { font-size: 22px; margin: 8px 0 0; }
  .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 30px; }
  .meta-item { background: #faf5f0; border-radius: 8px; padding: 12px; }
  .meta-item label { font-size: 11px; color: #888; display: block; }
  .meta-item span { font-size: 14px; font-weight: 600; }
  .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 11px; color: #999; }
</style>
</head>
<body>
<div class="header">
  <h1>CORTEX FORENSE</h1>
  <h2>${l.title}</h2>
  <p style="color:#666; margin:4px 0 0; font-size:13px;">${caseData.title}</p>
</div>

<div class="meta">
  <div class="meta-item"><label>Nº Processo</label><span>${caseData.case_number || "—"}</span></div>
  <div class="meta-item"><label>Vara / Tribunal</label><span>${caseData.court || "—"}</span></div>
  <div class="meta-item"><label>${l.perito}</label><span>${profile?.full_name || "—"}</span></div>
  <div class="meta-item"><label>${l.registration}</label><span>${profile?.registration_number || "—"}</span></div>
  <div class="meta-item"><label>${l.total}</label><span>${(evidences || []).length}</span></div>
  <div class="meta-item"><label>Status</label><span>${caseData.status === "concluido" ? (lang === "en" ? "Completed" : lang === "es" ? "Concluido" : "Concluído") : caseData.status === "arquivado" ? (lang === "en" ? "Archived" : "Arquivado") : (lang === "en" ? "In Progress" : lang === "es" ? "En Progreso" : "Em Andamento")}</span></div>
</div>

${caseData.description ? `<p style="color:#555; margin-bottom:24px;">${caseData.description}</p>` : ""}

${evidenceRows}

<div class="footer">
  <p>${l.generated} ${new Date().toLocaleString(lang === "en" ? "en-US" : lang === "es" ? "es-ES" : "pt-BR", { timeZone: "America/Sao_Paulo" })} (BRT)</p>
</div>
</body>
</html>`;

    return new Response(JSON.stringify({ html }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err: any) {
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
